# Aula 06 - Exercício 05

### Alunos:
 - Rafael Rodrigues Santana nº USP 7594375
 - Felipe Yoshio Guskuma nº USP 9292500

## Multilayer Perceptron para classificação do dataset Wine
Neste exercício utilizaremos a base de dados Wine, que consiste em 178 exemplos de dimensionalidade 13, separados em 3 classes. Os atributos dessa base de dados não estão normalizados, apresentando intervalos variados de valores.

- Carregue a base de dados wine e normalize entre 0 e 1 o valor dos seus atributos

In [0]:
from sklearn.datasets import load_wine
from sklearn.preprocessing import MinMaxScaler
import numpy as np

dados = load_wine()
dados.data
#print(list(data.target_names))
scaler = MinMaxScaler()
#np.shape(data.data)
norm_data = scaler.fit(dados.data)
print(scaler.fit(dados.data))
norm_data = scaler.data_max_
print(scaler.data_max_)
norm_data = scaler.transform(dados.data)
print(scaler.transform(dados.data))

MinMaxScaler(copy=True, feature_range=(0, 1))
[1.483e+01 5.800e+00 3.230e+00 3.000e+01 1.620e+02 3.880e+00 5.080e+00
 6.600e-01 3.580e+00 1.300e+01 1.710e+00 4.000e+00 1.680e+03]
[[0.84210526 0.1916996  0.57219251 ... 0.45528455 0.97069597 0.56134094]
 [0.57105263 0.2055336  0.4171123  ... 0.46341463 0.78021978 0.55064194]
 [0.56052632 0.3201581  0.70053476 ... 0.44715447 0.6959707  0.64693295]
 ...
 [0.58947368 0.69960474 0.48128342 ... 0.08943089 0.10622711 0.39728959]
 [0.56315789 0.36561265 0.54010695 ... 0.09756098 0.12820513 0.40085592]
 [0.81578947 0.66403162 0.73796791 ... 0.10569106 0.12087912 0.20114123]]


---
- Agora divida a base em conjunto de teste e treino. Utilize 20% da base para teste e 80% para treino.

In [0]:
from sklearn.model_selection import train_test_split


x = norm_data
y = data.target
X_train, X_test, y_train, y_test = train_test_split(x,y, test_size = round(178/5), train_size = round(4/5*178), shuffle = True)


---
- Treine 3 classificadores MLP (com `solver='sgd'`), variando o número de neurônios na camada escondida. Reporte o score dos classificadores nos conjuntos de treino e teste.

In [0]:
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score


clf = MLPClassifier(hidden_layer_sizes=(100,), max_iter=2000, alpha=0.0001,
                     solver='sgd', verbose=0,  random_state=21,tol=0.0001)

clf2 = MLPClassifier(hidden_layer_sizes=(5,), max_iter=50, alpha=0.00005,
                     solver='sgd', verbose=0,  random_state=21,tol=0.0001)

clf3 = MLPClassifier(hidden_layer_sizes=(50,), max_iter=1000, alpha=0.0002,
                     solver='sgd', verbose=0,  random_state=21,tol=0.0001)

clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)
print(accuracy_score(y_test, y_pred))


clf2.fit(X_train,y_train)
y_pred = clf2.predict(X_test)
print(accuracy_score(y_test, y_pred))


clf3.fit(X_train,y_train)
clf3.score(X_test,y_test)



0.9444444444444444
0.4166666666666667


/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


0.9444444444444444

---
- Selecione uma amostra de tamanho 10 do conjunto de testes. Selecione o classificador que apresentou maior acurácia no conjunto de testes e calcule, para cada elemento da amostra, a classe esperada, a classe obtida e a probabilidade estimada de cada classe

In [0]:
import pandas as pd

#classe esperada
print(y_test[0:10])

#classe obtida
clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)
print(y_pred[0:10])

#probabilidade estimada
#print(clf.predict_proba(X_test[0:10]))
pd.DataFrame(clf.predict_proba(X_test[0:10]), columns=clf.classes_)


[0 0 0 0 0 1 1 1 1 1]
[0 0 0 0 0 1 1 1 1 1]


0         1         2
0  0.950659  0.034147  0.015194
1  0.882248  0.113939  0.003813
2  0.946869  0.048797  0.004333
3  0.960116  0.036009  0.003874
4  0.918714  0.070381  0.010905
5  0.241353  0.724697  0.033950
6  0.362897  0.631703  0.005400
7  0.263553  0.428391  0.308056
8  0.029099  0.968054  0.002846
9  0.406982  0.570618  0.022399

---
- Agora sobre a mesma amostra escolhida anteriormente, selecione o classificador que apresentou menor acurácia no conjunto de testes e calcule, para cada elemento da amostra, a classe esperada, a classe obtida e a probabilidade esperada de cada classe.

In [0]:
import pandas as pd

#classe esperada
print(y_test[0:10])

#classe obtida
clf2.fit(X_train,y_train)
y_pred = clf2.predict(X_test)
print(y_pred[0:10])

#probabilidade estimada
#print(clf.predict_proba(X_test[0:10]))
pd.DataFrame(clf2.predict_proba(X_test[0:10]), columns=clf2.classes_)


[0 0 0 0 0 1 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1]


/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


0         1         2
0  0.340395  0.357792  0.301813
1  0.312181  0.407398  0.280421
2  0.316696  0.356041  0.327263
3  0.324415  0.371945  0.303640
4  0.307349  0.397910  0.294740
5  0.308378  0.451676  0.239946
6  0.277360  0.442180  0.280460
7  0.346634  0.422386  0.230980
8  0.241637  0.564071  0.194291
9  0.249927  0.523764  0.226310



---

- Faça uma análise das probabilidades calculadas por cada classificador nos exemplos corretos e relacione-as com a 'qualidade' dos mesmos.

No melhor classificador (clf), a probabilidade dos elementos preditos foi muito mais alta e precisa do que a probabilidade dos outros elementos, o que indica que a qualidade da predição foi muito maior comparada com a dos outros classificadores, que apresentaram probabilidades menos diferenciadas, além de conterem erros.

---
- Calcule, usando 10-fold cross-validation, a acurácia média da melhor configuração de classificador que você utilizou e seu desvio padrão

In [0]:
from sklearn.model_selection import StratifiedKFold


skf = StratifiedKFold(n_splits=10, shuffle=True)
skf.get_n_splits(x, y)

print(skf)  

score = []

for train_index, test_index in skf.split(x, y):
    #print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = x[train_index], x[test_index]
    y_train, y_test = y[train_index], y[test_index]
    clf.fit(X_train,y_train)
    y_pred = clf.predict(X_test)
    score.append(clf.score(X_test,y_test))
    print(clf.score(X_test,y_test))

print ('\n')
print (np.average(score))
print (np.std(score))

StratifiedKFold(n_splits=10, random_state=None, shuffle=True)
1.0
1.0
1.0
0.9444444444444444
1.0
0.9444444444444444
1.0
1.0
0.9411764705882353
0.9375


0.9767565359477125
0.028524920520712656
