# Aula 07 - Exercício 06
## KNN e Métricas de avaliação
### Alunos:
 - Felipe Yoshio Guskuma nºUSP 9292500
 - Rafael Rodrigues Santana nºUSP 7594375
 

# New Section

O dataset ["Breast Cancer Wisconsin"](https://archive.ics.uci.edu/ml/datasets/Breast+Cancer+Wisconsin+(Original) é um dataset que contém 699 instâncias, cada uma com 10 atributos númericos e 1 atributo correspondente a classe. A idéia do dataset é conseguir classificar um tumor como benigno ou maligno a partir de 10 variáveis descritivas. Foi adicionado um cabeçalho no arquivo original para facilitar seu manuseio.

- Notas:

  - **O dataset possui valores ausentes, representados por "?"**
  - A primeira variável do dataset é o ID de cada paciente. Essa variável **NÃO** deve ser utilizada no classificador 

---

- Carregue o dataset a partir do arquivo fornecido, substituindo os valores ausentes pela média dos valores daquela coluna. Utilize as classes `sklearn.impute.SimpleImputer` e a biblioteca `pandas`.

In [0]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer

data = pd.read_csv("breast-cancer-wisconsin.data", header = 0, usecols = range(1,11), na_values = '?')
print(data)
imp_mean = SimpleImputer(missing_values = np.nan, strategy = 'mean')
imp_mean.fit(data)
datap = imp_mean.transform(data)
print(datap)



---
- Centralize e normalize os dados e separe 80% do conjunto para treino e 20% para testes. Faça uma divisão dos dados de maneira **estratificada**.

In [0]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler().fit(datap)
X = scaler.transform(datap)
Y = datap[:,9]

train_x, test_x, train_y, test_y = train_test_split(X, Y, test_size = 0.2, random_state = 1, stratify = Y)



---

- Faça classificação no conjunto de testes utilizando 4 classificadores KNN, com K=3 e 15 e p=1 e 2 (distância de Minkowski/Euclidiana). Para cada classificador, calcule e exiba a matriz de confusão bem como a acurácia do classificador. **Para calcular a acurácia, utilize APENAS a matriz de confusão.**

In [0]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix

k = 3
model = KNeighborsClassifier(n_neighbors=k, p = 1)
# Train the model using the training sets
model.fit(train_x,train_y)

#Predict Output
pred_y1= model.predict(test_x) 

confm = confusion_matrix(test_y, pred_y1)
print(confm)
acc = np.trace(confm) / np.sum(confm)
print(acc)
##############################################################################
k = 15
model = KNeighborsClassifier(n_neighbors=k, p = 2)
# Train the model using the training sets
model.fit(train_x,train_y)

#Predict Output
pred_y2= model.predict(test_x)

confm = confusion_matrix(test_y, pred_y2)
print(confm)
acc = np.trace(confm) / np.sum(confm)
print(acc)
##############################################################################
k = 3
model = KNeighborsClassifier(n_neighbors=k, p = 1)
# Train the model using the training sets
model.fit(train_x,train_y)

#Predict Output
pred_y3= model.predict(test_x) 

confm = confusion_matrix(test_y, pred_y3)
print(confm)
acc = np.trace(confm) / np.sum(confm)
print(acc)
##############################################################################
k = 15
model = KNeighborsClassifier(n_neighbors=k, p = 2)
# Train the model using the training sets
model.fit(train_x,train_y)

#Predict Output
pred_y4= model.predict(test_x)
confm = confusion_matrix(test_y, pred_y4)
print(confm)
acc = np.trace(confm) / np.sum(confm)
print(acc)

[[92  0]
 [ 1 47]]
0.9928571428571429
[[90  2]
 [ 1 47]]
0.9785714285714285
[[92  0]
 [ 1 47]]
0.9928571428571429
[[90  2]
 [ 1 47]]
0.9785714285714285




---
Agora vamos analisar um problema de classificação não binário. Para isso, vamos utilizar o conjunto Iris. Repetindo os passos anteriores:
- Carregue o conjunto Iris
- Centralize e normalize os dados
- Separe o conjunto, de maneira **NÃO** estratificada, em 50% treino e 50% teste (a ideia é que o classificador tenha um erro maior)
- Utilize um classificador KNN com K=1 para predizer o conjunto de teste. Essa predição será utilizado posteriormente.


In [0]:
from sklearn.datasets import load_iris

x, y = data = load_iris(return_X_y=True)

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler().fit(x)
X = scaler.transform(x)

train_x, test_x, train_y, test_y = train_test_split(x, y, test_size = 0.5, random_state = 1, stratify = None)

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix

k = 1
model = KNeighborsClassifier(n_neighbors=k, p = 1)
# Train the model using the training sets
model.fit(train_x,train_y)

#Predict Output
pred_y1= model.predict(test_x) 



---

- Mostre a matriz de confusão do conjunto de teste e em seguida, para cada variável do conjunto, mostre sua matriz de confusão binária.
  - Dica: Pesquise sobre o método `numpy.delete`

In [0]:
confm = confusion_matrix(test_y, pred_y1)
print(confm)
acc = np.trace(confm) / np.sum(confm)
print(acc)

#######################################################
m = np.zeros((2,2))
k = len(confm)
for i in range(k):
  m[0][0] = confm[i][i]
  m[0][1] = np.sum(confm[i,:]) - confm[i][i]
  m[1][0] = np.sum(confm[:,i]) - confm[i][i]
  m[1][1] = np.sum(confm)-m[1][0]-m[0][1]-m[0][0]
  print("classe", i )
  print(m)

[[24  0  0]
 [ 0 24  0]
 [ 0  4 23]]
0.9466666666666667
classe 0
[[24.  0.]
 [ 0. 51.]]
classe 1
[[24.  0.]
 [ 4. 47.]]
classe 2
[[23.  4.]
 [ 0. 48.]]




---

- Utilizando as matrizes de confusão binárias calculadas acima, calcule o **Recall** e **Precisão** de cada variável do conjunto.
  - Dica 1: Lembre-se que ao calcular a matriz de confusão binária para cada classe, obtemos os valores VP, FP, FN e VN.
  - Dica 2: Lembre-se que Recall é calculado por $\frac{VP}{VP+FN}$ e Precisão por  $\frac{VP}{VP+FP}$.

In [0]:
for i in range(k):
  m[0][0] = confm[i][i]
  m[0][1] = np.sum(confm[i,:]) - confm[i][i]
  m[1][0] = np.sum(confm[:,i]) - confm[i][i]
  m[1][1] = np.sum(confm)-m[1][0]-m[0][1]-m[0][0]
  
  
  print("classe", i )
  recall = m[0][0]/(m[0][0]+m[1][0]) 
  print(recall)
  precisao = m[0][0]/(m[0][0]+m[0][1]) 
  print(precisao)

classe 0
1.0
1.0
classe 1
0.8571428571428571
1.0
classe 2
1.0
0.8518518518518519




---
Considere o conjunto de dados abaixo, onde são representados um conjunto de $n$ pontos que podem ser classificados em duas classes: verde ou azul. **Todo** o conjunto pode ser visto na imagem abaixo. O ponto preto $q$ é um ponto de consulta, cuja classe é desconhecida. Suponha que foi usado um classificador do tipo KNN com distância euclidiana para classificar esse ponto.


![](https://drive.google.com/uc?export=view&id=1e7oUOHOwyFZ8R1Xy0FPUJ8n_M0YGB2_d)


- Qual a saída desse classificador para K=3?

**O ponto q será classificado como azul, já que os três pontos mais próximos são azuis**



---

- E para K=9?

**O ponto q será classificado como verde, já que entre os nove pontos mais próximos seis são verdes e apenas três são azuis**



---

 - E para o caso extremo de K=$n$? A posição de $q$ no espaço interfere nesse resultado? Justifique.

**No caso extremo será classificado como verde, pois a maioria dos pontos são verdes. A posição do ponto não interfere, pois a análise engloba todos os pontos.**