# PolynomialFeatures

Como a documentação do sklearn não estava muito clara, achei melhor esclarecer como funciona a regressão polinomial.

Suponha que temos uma base de dados $D$ que possui variáveis de nome $A, B$ e valor de função $T$. Uma observação dessas variáveis é dada por $(a_0, b_0)$, com valor $t_0$. 


* Uma aproximação linear de $t_0$ (suponha que os valores  $\beta_i$ foram encontrados utilizando algum algoritmo como mínimos quadrados) pode ser dada por:

  $t^{(1)}_0=f^{(1)}(a_0, b_0)= \beta^{(1)}_0 + \beta^{(1)}_1 a_0 + \beta^{(1)}_2 b_0 $

* Uma aproximação quadrática (polinômio de segundo grau) da função pode ser vista da forma:

  $t^{(2)}_0=f^{(2)}(a_0, b_0)= \beta^{(2)}_0 + \beta^{(2)}_1 a_0 + \beta^{(2)}_2 b_0 + \beta^{(2)}_4 a_0^2 + \beta^{(2)}_5 b_0^2 + \beta^{(2)}_7 a_0 b_0$

* Note que podemos encarar "aproximar via função quadrática" como "aproximar via função linear" se considerarmos $a_0^2$, $b_0^2$ e $a_0b_0$ como novas variáveis, $c_0, d_0$ e $e_0$ no problema:

  $t^{(3)}_0=f^{(3)}(a_0, b_0, c_0, d_0, e_0)= \beta^{(3)}_0 + \beta^{(3)}_1 a_0 + \beta^{(3)}_2 b_0 + \beta^{(3)}_3 c_0 + \beta^{(3)}_4 d_0 + \beta^{(3)}_5 e_0$

* Basta que realizemos a transformação de $(a, b)$ para $(a, b, c, d, e)$, com $c=a^2, d=b^2$ e $e=ab$.


---


Felizmente a classe **PolynomialFeatures** é bastante útil nesse momento, pois ela nos permite realizar essa transformação facilmente, de forma que consigamos utilizar a mesma sintaxe utilizado anteriormente para adaptar nosso modelo linear.

Basta inicializar um polinômio e transformar o conjunto de dados, por exemplo:

```python
p = PolynomialFeatures(degree=grau)
X_Transf = p.fit_transform(X)
```

E agora ao invés de adaptar nosso modelo linear ao conjunto X, adaptamos ao conjunto X_Transf.


In [2]:
from sklearn.preprocessing import PolynomialFeatures
import numpy as np

#3 observações de 2 variáveis

x = np.array([[1, 2],
              [3, 4],
              [5, 6]])

# Utilizando um polinomio de grau 3
p = PolynomialFeatures(degree=2)

X_Transf = p.fit_transform(x)
print(p.get_feature_names())
print(X_Transf)

['1', 'x0', 'x1', 'x0^2', 'x0 x1', 'x1^2']
[[ 1.  1.  2.  1.  2.  4.]
 [ 1.  3.  4.  9. 12. 16.]
 [ 1.  5.  6. 25. 30. 36.]]
